### PR TITLE
Support for WX Python Phoenix

### LINKED ISSUE #171: wxPython 4 compatibility: wx.Menu does not have SetCheckable method
Hi,

As of March 13, 2018 build of NVDA next snapshots, GUI is powered by wxPython 4. This breaks Remote add-on because:

ERROR - globalPluginHandler.initialize (09:19:12.835):
Error initializing global plugin <class 'globalPlugins.remoteClient.GlobalPlugin'>
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 32, in initialize
  File "C:\Users\User\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 56, in __init__
  File "C:\Users\User\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 104, in create_menu
AttributeError: 'MenuItem' object has no attribute 'SetCheckable'

This is Remote add-on 2.1 on Windows 10. I propose resolving this as soon as possible so NVDA next branch users can test compatibility between this add-on and NVDA Core. Thanks.

### PR DESCRIPTION
**Pull request by leonardder**
Closes #171

See nvaccess/nvda#7104 and nvaccess/nvda#8084

### CODE REVIEW

File: addon/globalPlugins/remoteClient/__init__.py [hunk 1]
```diff
@@ -100,8 +100,11 @@ def create_menu(self):
 		self.disconnect_item.Enable(False)
 		gui.mainFrame.sysTrayIcon.Bind(wx.EVT_MENU, self.on_disconnect_item, self.disconnect_item)
 		# Translators: Menu item in NvDA Remote submenu to mute speech and sounds from the remote computer.
-		self.mute_item = self.menu.Append(wx.ID_ANY, _("Mute remote"), _("Mute speech and sounds from the remote computer"))
-		self.mute_item.SetCheckable(True)
+		if dialogs.WX_VERSION<=3:
+			self.mute_item = self.menu.Append(wx.ID_ANY, _("Mute remote"), _("Mute speech and sounds from the remote computer"))
+			self.mute_item.SetCheckable(True)
+		else:
```
Comment (tspivey) [inline addon/globalPlugins/remoteClient/__init__.py]: This works on the WX Python 3.0 I have, so the first part of this if is unneeded.

**Comment by tspivey** [comment]
This doesn't load with WXPython 3.
```
ERROR - globalPluginHandler.listPlugins (22:27:31.980):
Error importing global plugin remoteClient
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 22, in listPlugins
  File "C:\Users\tyler\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 36, in <module>
  File "C:\Users\tyler\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\dialogs.py", line 19, in <module>
AttributeError: 'module' object has no attribute 'Center_ON_SCREEN'
```

**Comment by tech55541** [comment]
Seems like this fix made the add-on work in latest production version of NVDA, any time frame of official add-on release?
